sonar.projectKey=portfolio-landing-page
sonar.projectName=Portfolio Landing Page - DevOps Engineer
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,**/*.test.js

# Path to test directories
sonar.tests=.
sonar.test.inclusions=**/*.test.js

# Coverage reports
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js,jest.config.js

# Language
sonar.language=js
