apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- ingress.yaml  # Uncommented

images:
- name: 476415713645.dkr.ecr.us-east-1.amazonaws.com/portfolio-landing-page
  newTag: latest  # Can be overridden by ArgoCD
