apiVersion: v1
kind: ServiceAccount
metadata:
  name: portfolio-sa
  namespace: portfolio
  annotations:
    # This ARN comes from: terraform/live/dev/apps/portfolio/irsa output
    eks.amazonaws.com/role-arn: arn:aws:iam::476415713645:role/pamfes-dev-cluster-portfolio-irsa
  labels:
    app: portfolio
