- hosts: pamfes_frontend
  become: true
  roles:
    - nginx
    #- prometheus

# - hosts: monitors
#   become: true
#   roles:
#     - prometheus

- hosts: all
  become: true
  roles:
    - puppet

- name: Manage SSH access
  hosts: all
  become: true
  roles:
   - ssh_access